spring:
  application:
    name: MyDrive
  profiles:
    active: dev # nginx.conf env

  mvc:
    favicon:
      enable: false
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: PT60M